version: '3.7' # composeファイルのバーション指定
services:
  takumiweb:
    # service名
    build: . # ビルドに使用するDockerfileがあるディレクトリ指定
    tty: true # コンテナの起動永続化
    volumes:
      - .:/app # マウントディレクトリ指定
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: takumi
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: takumiweb
    ports:
      - 5432:5432
